apiVersion: v1
kind: Service
metadata:
  name: sd-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: sd-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30230